### ISSUE TITLE
Adding CSS files

### ISSUE THREAD

**Issue by Kakroo** [cyberbuddy-io/open-source-contribution-for-beginners#103]
I am going to add a new CSS file in a CSS folder which i will be creating.

**Comment by lovishprabhakar02** [comment]
Go ahead! @Kakroo

**Comment by cyberbuddy-manas** [comment]
@Kakroo Finally we've got CSS folder in our repository for others to contribute to. All thanks to your contribution. Hope to see more from you in the future. Have a great New Year
