### ISSUE TITLE
Adding Java files

### ISSUE THREAD

**Issue by BhavyamSharma7** [cyberbuddy-io/open-source-contribution-for-beginners#109]
i will create a new folder for java files. Please assign me this issue @lovishprabhakar02 .

**Comment by cyberbuddy-manas** [comment]
@BhavyamSharma7 Thank you for creating the first issue for the Java Programs. Everyone will be able to add their Java programs in your folder and I'll also be pinning this issue for others to easily find it. Hope to see more contributions from you in the future.

**Comment by ayush8446** [comment]
I added a Java program to check whether a number is prime or not

**Comment by ravneetzz** [comment]
adding a java program to check armstrong number #109

**Comment by ravneetzz** [comment]
adding a java program to check palindrome number #109
