### ISSUE TITLE
Adding Android code using java

### ISSUE THREAD

**Issue by SayamSharm** [cyberbuddy-io/open-source-contribution-for-beginners#11]
I will create a new folder for Android code scripts and keep adding all the apps I work on. Please assign this issue to me @lovishprabhakar02

**Comment by lovishprabhakar02** [comment]
All yours! @SayamSharm

**Comment by lovishprabhakar02** [comment]
Closed #11 with #14

**Comment by cyberbuddy-manas** [comment]
@SayamSharm I was going through your commit. Can you please share what exactly is your commit about?
