### ISSUE TITLE
adding beginner level java programs

### ISSUE THREAD

**Issue by Ishnoor-kaur** [cyberbuddy-io/open-source-contribution-for-beginners#112]
i will add basic java programs . Please assign me this issue @lovishprabhakar02

**Comment by cyberbuddy-manas** [comment]
@Ishnoor-kaur A very Happy New year to you. May this year be more prosperous and joy filling for you. I'll be assigning this issue to you.

**Comment by cyberbuddy-manas** [comment]
@Ishnoor-kaur Also @BhavyamSharma7 has already created the folder for Java Program so make sure you add your program in the same.
