### ISSUE TITLE
Adding Tailwind CSS files

### ISSUE THREAD

**Issue by StartCodeingWithSayam** [cyberbuddy-io/open-source-contribution-for-beginners#117]
As i am learning tailwind css i want to contribute to this @lovishprabhakar02  please assign this issue to me

**Comment by cyberbuddy-manas** [comment]
Hey @StartCodeingWithSayam. It's a good issue that you've opened. Just make sure you create a new folder with the name of Tailwind. Thanks for contributing 👍🏼
