### ISSUE TITLE
Adding a New CPP File

### ISSUE THREAD

**Issue by pacific-prashant** [cyberbuddy-io/open-source-contribution-for-beginners#12]
I'll be creating a new folder to add a CPP file that I created for my college syllabus practice

**Comment by lovishprabhakar02** [comment]
Hey @pacific-prashant , a junior has approached me, he's currently learning cpp so i think we should give him a chance to add these files. So if you would close this issue, he can work on it

**Comment by lovishprabhakar02** [comment]
Hey @pacific-prashant, the c++ folder has been created in the repository by another contributor. So you can add your files in that folder now

**Comment by lovishprabhakar02** [comment]
closed #12 with #30
