### ISSUE TITLE
Python Programs

### ISSUE THREAD

**Issue by Jatin-Miglani** [cyberbuddy-io/open-source-contribution-for-beginners#128]
I will contribute to Python Programs

**Comment by lovishprabhakar02** [comment]
Go ahead! @Jatin-Miglani

**Comment by cyberbuddy-manas** [comment]
Hi @Jatin-Miglani. It's been a while since you opened this issue and there hasn't been any activity regarding this issue. We are closing this issue but in future if you want, you open it again if you wish to work on it. Keep Striving!!
