### ISSUE TITLE
Adding Java Script files

### ISSUE THREAD

**Issue by sanviii** [cyberbuddy-io/open-source-contribution-for-beginners#15]
I will be adding a new java script code which would be calculating whether a number is prime or not. @lovishprabhakar02

**Comment by lovishprabhakar02** [comment]
Closed #15 with #16

**Comment by pacific-prashant** [comment]
Adding a new JS code in which I have created a form.

**Comment by sanviii** [comment]
@lovishprabhakar02 I am going to add a new JS file to calculate area of shapes.

**Comment by pacific-prashant** [comment]
Adding a clock js program #15

**Comment by Brandon-Amezcua** [comment]
@lovishprabhakar02 I would like to add to the area of shapes file by calculating the area of a circle, sphere, and cube

**Comment by cyberbuddy-manas** [comment]
Hi @Brandon-Amezcua. Go ahead....you have the green signal.

**Comment by lovishprabhakar** [comment]
> @lovishprabhakar02 I would like to add to the area of shapes file by calculating the area of a circle, sphere, and cube

Go ahead! @Brandon-Amezcua
