### ISSUE TITLE
Application Development  (with ML)

### ISSUE THREAD

**Issue by logic-404** [cyberbuddy-io/open-source-contribution-for-beginners#17]
I will develop desktop/android applications using python and kivy.

**Comment by lovishprabhakar02** [comment]
All yours! @logic-404

**Comment by cyberbuddy-manas** [comment]
@logic-404 Could you please debrief a little about the idea behind the applications you'll be contributing. What will be it all about?

**Comment by logic-404** [comment]
I have some applications I have been working on. I'm mainly gonna focus on making some clones  to famous social medi apps rn (with advanced features ofc).  I also want to make some original functional apps using python

**Comment by cyberbuddy-manas** [comment]
Hi @logic-404 . We see that their hasn't been any update regarding this issue so we plan on to close this issue for now. In future if you want to contribute regarding the same, you can open the same issue again.
