### ISSUE TITLE
Adding CPP Files

### ISSUE THREAD

**Issue by kartikthakur7107** [cyberbuddy-io/open-source-contribution-for-beginners#19]
Since I am learning C++ I"ll be adding cpp files, Please assign me the issue.

**Comment by lovishprabhakar02** [comment]
Go ahead! @kartikthakur7107

**Comment by lovishprabhakar02** [comment]
Good work @kartikthakur7107 , now as the c++ folder has been created, if you want to add any more c++ files, you can create issues for them.

**Comment by lovishprabhakar02** [comment]
Closed #19 with #20

**Comment by lovishprabhakar02** [comment]
Closed #19 with #20

**Comment by cyberbuddy-manas** [comment]
Let's make this a pinned issue @lovishprabhakar02  because many people would like to add CPP codes in the org. So they won't be needing to create new issue rather they can comment on this one. This way referencing will be done on this issue only and managing CPP codes will be easier.

**Comment by lovishprabhakar02** [comment]
Done @cyberbuddy-manas

**Comment by pacific-prashant** [comment]
I'm adding a new CPP code that will reverse an array

**Comment by Ishant281o** [comment]
Hey, @lovishprabhakar02 I am adding a CPP program of copy constructor. Please assign it.

**Comment by StartCodeingWithSayam** [comment]
I have some of cpp files which I want to commit here so @lovishprabhakar02  please merge them

**Comment by Ravnoor12** [comment]
I want to add some c++ files, kindly review and merge them.

**Comment by rahul-nangla** [comment]
Hey there! i'm going to contribute a cpp program which will sum prime numbers of an array #19

**Comment by lovishprabhakar02** [comment]
I would like to add some files

**Comment by Sukhmeet-0** [comment]
I'm adding a cpp file which calculates area #19

**Comment by anmolghai02** [comment]
I want to add some c++ files, please assign this issue to me @lovishprabhakar02

**Comment by rswalia** [comment]
I would like to add some basic cpp theory files. Please assign this issue to me @lovishprabhakar02

**Comment by vanshita-mahajan** [comment]
I'm adding a C++ file which will sum the diagonal elements of an array#19

**Comment by pacific-prashant** [comment]
I'm adding a CPP file to insert the linked list at the index.#19

**Comment by rswalia** [comment]
I'm adding an array file of cpp #19 @lovishprabhakar02

**Comment by rana-mansi** [comment]
I'm adding a c++ program for linear search#19

**Comment by Samar2410** [comment]
I'm adding a cpp inheritance program#19

**Comment by StartCodeingWithSayam** [comment]
You have not commit my changes to c++ folder I have 3 files 1 for binnery search ,1 lenier search,and 1 of swapingalternatives 
Please merge them @lovishprabhakar02

**Comment by Samar2410** [comment]
I want to add a cpp program of stack implementation using array#19

**Comment by ravneetzz** [comment]
I'm adding a bubble sort program. @lovishprabhakar02 pls assign this issue #19

**Comment by Ishant281o** [comment]
Adding virtual function C++ program #19

**Comment by rswalia** [comment]
Hey, @lovishprabhakar02 I am adding a CPP program of conditional statement. Please assign it #19

**Comment by akantsalaria1** [comment]
Hey, @lovishprabhakar02 I am adding a CPP program of conditional statement. Please assign it to me.

**Comment by nikhil-basra** [comment]
I'm adding a C++ program of rectangular hollow pattern. @lovishprabhakar02 pls assign my issue.

**Comment by Samar2410** [comment]
I want to add a cpp file about insertion in a linked list.

**Comment by Ishant281o** [comment]
I am adding a filehandling program cpp.

**Comment by love-sh** [comment]
I would like to add a program that shows the range limits of datatypes. Please assign this issue to me @lovishprabhakar02

**Comment by rswalia** [comment]
I'm adding a string swap cpp file.@lovishprabhakar02 pls assign my issue

**Comment by Ishant281o** [comment]
Adding friend function cpp file. #19

**Comment by kingmask420** [comment]
Adding 2 cpp files . kindly merge them

**Comment by cyberbuddy-manas** [comment]
Cool @kingmask420. Welcome to the league. Keep Contributing!!

**Comment by pacific-prashant** [comment]
i'm adding a cpp file

**Comment by ramnaresh8** [comment]
hey! I'm adding a CPP program of power recursion. @lovishprabhakar02  please assign my issue.

**Comment by lovishprabhakar02** [comment]
Go ahead! @ramnaresh8

**Comment by ramnaresh8** [comment]
adding a cpp file Indirect recursion

**Comment by ramnaresh8** [comment]
Adding a cpp file of indirect recursion #19

**Comment by ramnaresh8** [comment]
tree recursion using c++

**Comment by ramnaresh8** [comment]
adding a pascle triangle file #19

**Comment by cyberbuddy-manas** [comment]
@ramnaresh8 Great one!! Keep going. Why don't you add a new folder for Patterns and add your file in a folder inside this with the name of the language your program is in. Give it a shot!!

**Comment by ravneetzz** [comment]
adding a cpp program for operator overloading #19

**Comment by ravneetzz** [comment]
adding a cpp program to display dynamic object #19

**Comment by ravneetzz** [comment]
adding selection sort  cpp program #19

**Comment by Ravneet16** [comment]
I'm adding  Bank Automation CPP program. @ilovishprabhakar  assign my issue.

**Comment by pacific-prashant** [comment]
adding a single prime number CPP program

**Comment by ravneetzz** [comment]
Peviously there was a issue in the file I have added. I am adding new files inplace of them and deleting the older one. #19

**Comment by Ravneet16** [comment]
Adding a C++ file to check whether a Number is Armstrong or not ?  cyberbuddy-io#19

**Comment by Ravneet16** [comment]
Adding a simple program to demonstrate the use of break statement.#19

**Comment by ravneetzz** [comment]
Adding matrix multiplication program #19

**Comment by ravneetzz** [comment]
adding fibonacci series program #19

**Comment by Ravneet16** [comment]
adding a program to demonstrate diamond problem or ambiguity problem #19

**Comment by ravneetzz** [comment]
adding a program to demonstrate use of friend class #19

**Comment by ravneetzz** [comment]
adding a program to find the position of cursor #19

**Comment by Samar2410** [comment]
Adding a vector program #19
