### ISSUE TITLE
Adding GoLang files

### ISSUE THREAD

**Issue by ArjunMalhotra07** [cyberbuddy-io/open-source-contribution-for-beginners#21]
trying out Go. May as well add its files

**Comment by lovishprabhakar02** [comment]
Go  ahead! @ArjunMalhotra07

**Comment by ArjunMalhotra07** [comment]
Hey! I wanted to know what do i do next? I have sent a pull request. Now
u'll merge it by yourself or I have to do something to merge it? Could get
a little help here
Thanks

**Comment by lovishprabhakar02** [comment]
Hey @ArjunMalhotra07, your PR is now merged. Do keep in mind that when you create a PR,  you should write the issue number, which it refers to, in the description.

**Comment by lovishprabhakar02** [comment]
Good going @ArjunMalhotra07 ! Keep it up, I am going to pin this issue so that other people can also contribute in GoLang.

**Comment by ArjunMalhotra07** [comment]
Thanks✌️
