### ISSUE TITLE
Adding a CPP file 

### ISSUE THREAD

**Issue by Ishant281o** [cyberbuddy-io/open-source-contribution-for-beginners#34]
I am adding a program of Copy constructor in CPP

**Comment by lovishprabhakar02** [comment]
Go ahead! @Ishant281o, and the next time you want to add a C++ file, you can simply create a Pull Request and mention #19 in its description.

**Comment by cyberbuddy-manas** [comment]
@lovishprabhakar02  I see you have already instructed @Ishant281o regarding the correct way to contribute. So either of you can close this issue.

**Comment by lovishprabhakar02** [comment]
Closing this issue and @Ishant281o you can proceed as i explained earlier
