### ISSUE TITLE
Adding Python files

### ISSUE THREAD

**Issue by ritishbhardwaj** [cyberbuddy-io/open-source-contribution-for-beginners#35]
#36 little aware of oops concepts!!! there is little code using oops concept.

**Comment by deepkaurb** [comment]
Adding a python file which will manage the food system

**Comment by Kritikmahajan** [comment]
I will add the dictionary methods

**Comment by cyberbuddy-manas** [comment]
> I will add the dictionary methods

Cool!! Now that you know the proper method of contributing, why not try it once more to make your concepts strong.

**Comment by Vishdarkbright21** [comment]
I want to add some more codes  for python can you assign me pls.

**Comment by i-otaku** [comment]
I would like to add rock paper scissors game. Please assign this issue to me @lovishprabhakar02

**Comment by Ravneet16** [comment]
Adding a python file demonstrating the first n prime numbers  but less than 9999  using nested for loops #35

**Comment by Ravneet16** [comment]
Adding a python file  demonstrating the Latin square  program #35
