### ISSUE TITLE
Add the readme to github pages

### ISSUE THREAD

**Issue by cyberbuddy-manas** [cyberbuddy-io/open-source-contribution-for-beginners#4]
Let's add all the points and create a website using the default option in github pages. Assign this issue to me so that I can start contributing to this repository. @lovishprabhakar02

**Comment by lovishprabhakar02** [comment]
Go ahead! @cyberbuddy-manas

**Comment by cyberbuddy-manas** [comment]
Yeah well I just checked and the thing is we don't really need a different folder as I was expecting but rather a new .yml file for selecting a theme. For now let's go with the default one and in future, we'll see what we can do about it.
