### ISSUE TITLE
web development roadmap

### ISSUE THREAD

**Issue by payalpm** [cyberbuddy-io/open-source-contribution-for-beginners#400]

**Comment by payalpm** [comment]
plz add this my first issue

**Comment by trakshan-mishra** [comment]
Can you please elaborate more on this issue?

**Comment by junaidahamed800** [comment]
Can I get more details regarding this about how to add a roadmap

**Comment by lovishprabhakar** [comment]
> Can I get more details regarding this about how to add a roadmap

@payalpm

**Comment by junaidahamed800** [comment]
Hey @payalpm can I get more details regarding this about how to add a roadmap
