### ISSUE TITLE
Updating the Html form project

### ISSUE THREAD

**Issue by junaidahamed800** [cyberbuddy-io/open-source-contribution-for-beginners#401]
@lovish-prabhakar Hi i would contribute to this issue by further developing the form project.

**Comment by junaidahamed800** [comment]
can i get guidance how to get this code into my device and again pushing it

**Comment by lovishprabhakar** [comment]
Hi @junaidahamed800! You can get the full guidance from the repository's [Readme file](https://github.com/cyberbuddy-io/open-source-contribution-for-beginners/blob/master/README.md)
