### ISSUE TITLE
Adding a python script to scrape British Airways Reviews

### ISSUE THREAD

**Issue by t-iuy987** [cyberbuddy-io/open-source-contribution-for-beginners#415]
I will be adding a python script i wrote to scrape the reviews of British Airways from [here ](https://www.airlinequality.com/airline-reviews/british-airways). Please assign this issue to me @lovishprabhakar

**Comment by RashiChauhan67** [comment]
Hi @t-iuy987 I would like to contribute to your repository and resolve this issue. I will add the script, kindly assign it to me.
