### ISSUE TITLE
first open source

### ISSUE THREAD

**Issue by AishwaryJain07** [cyberbuddy-io/open-source-contribution-for-beginners#425]
Namaste,
I'm Aishwary Jain and I'll be contributing my first open source here

**Comment by Nyxoy77** [comment]
Hey 
I will like to make my first open source contribution on this repo i am new to this world of open source so , I request for your assistance

**Comment by AishwaryJain07** [comment]
@Nyxoy77 contact me on my linkedin "linkedin.com/in/aishwary-jain-555b042a7"
i can help you there

**Comment by Lily3-2** [comment]
I look forward to making simple open-source contributions to this repository if you need someone. Please let me know if there is any work.

**Comment by Nyxoy77** [comment]
> @Nyxoy77 contact me on my linkedin "linkedin.com/in/aishwary-jain-555b042a7" i can help you there
sure
