### ISSUE TITLE
Adding C files

### ISSUE THREAD

**Issue by Sayali-0506** [cyberbuddy-io/open-source-contribution-for-beginners#52]
I am learning C language, so I want to add .C files, Please assign me the issue.

**Comment by lovishprabhakar02** [comment]
Go ahead! @Sanju0506

**Comment by Sanju0506** [comment]
Can you create one folder for C Language. So that, i can add files in that.

**Comment by lovishprabhakar02** [comment]
You should create one yourself @Sanju0506 as you will get practice of it. Just create one on your Local and push it to Remote

**Comment by ramnaresh8** [comment]
adding a factorial program using recursion in c language #52

**Comment by lovishprabhakar02** [comment]
Go ahead! / @ramnaresh8
