### ISSUE TITLE
SOME PYTHON CODES To add

### ISSUE THREAD

**Issue by Vishdarkbright21** [cyberbuddy-io/open-source-contribution-for-beginners#58]
I WANT TO ADD SOME PYTHON CODES IN PYTHON SECTION ! CAN YOU ASSIGN ME

**Comment by lovishprabhakar02** [comment]
@Vishdarkbright21 no need to create a new issue for python. Just comment the same in #35 and you will be assigned the issue.

**Comment by Vishdarkbright21** [comment]
Ohh okay 👍 thanks ! @lovishprabhakar02
