### ISSUE TITLE
New JavaScript Code

### ISSUE THREAD

**Issue by divyamkapoor** [cyberbuddy-io/open-source-contribution-for-beginners#6]
### I have recently started learning JS, so I am adding a basic code.

1. Adding a folder in the root folder.
2. Adding the JS file.

Please assign this issue to me @lovishprabhakar02

**Comment by lovishprabhakar02** [comment]
Go ahead! @divyamkapoor

**Comment by lovishprabhakar02** [comment]
@divyamkapoor as a JavaScript folder has already been created by another contributor, you can add your files in that folder

**Comment by cyberbuddy-manas** [comment]
hi @divyamkapoor. We see that their hasn't been any update regarding this issue so we plan on to close this issue for now. In future if you want to contribute regarding the same, you can open the same issue again.
