### ISSUE TITLE
Adding HTML files

### ISSUE THREAD

**Issue by Samar2410** [cyberbuddy-io/open-source-contribution-for-beginners#62]
I'm adding an html file

**Comment by lovishprabhakar02** [comment]
Go ahead! @Samar2410

**Comment by rswalia** [comment]
I would like to add some Html files @lovishprabhakar02 plz assign it.

**Comment by lovishprabhakar02** [comment]
@Samar2410 as the HTML folder has been added by @rswalia , you can add your file in it and create pull request again

**Comment by cyberbuddy-manas** [comment]
Cool, @lovishprabhakar02 what we can do is, we can set this folder as the source for GitHub pages, or better I'll add Vercel for this folder so that those who contribute to this folder can view there web pages on google.

**Comment by lovishprabhakar02** [comment]
Good Idea @cyberbuddy-manas 

> Cool, @lovishprabhakar02 what we can do is, we can set this folder as the source for GitHub pages, or better I'll add Vercel for this folder so that those who contribute to this folder can view there web pages on google.

**Comment by cyberbuddy-manas** [comment]
@rswalia Thank you for your contribution. You can view your html file here [https://opensource.cyberbuddy.io/Forms.html](https://opensource.cyberbuddy.io/Forms.html). Keep Contributing and improving.

**Comment by cyberbuddy-manas** [comment]
@Samar2410 Thank you for your contribution. You can view your html file here [https://opensource.cyberbuddy.io/Html.html](https://opensource.cyberbuddy.io/Html.html). Keep Contributing and improving.

**Comment by ilearn-code** [comment]
i'm adding a basic banking system website. @lovishprabhakar02 assign my issue #62

**Comment by Samar2410** [comment]
I am adding an HTML file about navigation menu.

**Comment by Samar2410** [comment]
I am adding an HTML file(web page for a gym).

**Comment by cyberbuddy-manas** [comment]
@Samar2410 Cool, will merge your pull request after verification.
