### ISSUE TITLE
New Python Code

### ISSUE THREAD

**Issue by cyberbuddy-manas** [cyberbuddy-io/open-source-contribution-for-beginners#7]
Well I have done DSA majorly in Python only so I thought I shall add a few codes in python directory of this repo so that I can stay in touch with GitHub. Please assign this issue to me @lovishprabhakar02 . Also why don't you create some issue so that you don't losse your practice.

### Things am gonna do:

1. Create a directory for python
2. Add files for python codes.

**Comment by lovishprabhakar02** [comment]
All yours! @cyberbuddy-manas , and sure, I will add cpp code in a while

**Comment by cyberbuddy-manas** [comment]
@lovishprabhakar02 CPP folder is soon going to be added by @pacific-prashant and I shall wait for someone to add python issue so that other people get a better chance at this.
