### ISSUE TITLE
Improving Indentation in readme file

### ISSUE THREAD

**Issue by pacific-prashant** [cyberbuddy-io/open-source-contribution-for-beginners#8]
This issue is in reference to #1 .  I'll be improving the indentation of the readme documentation. Please assign this issue to me @lovishprabhakar02

**Comment by lovishprabhakar02** [comment]
Go ahead! @pacific-prashant

**Comment by pacific-prashant** [comment]
@lovishprabhakar02 please merge the pull request I shared.

**Comment by lovishprabhakar02** [comment]
Closed #8 with #9
