### ISSUE TITLE
Adding Data Structure files 

### ISSUE THREAD

**Issue by pacific-prashant** [cyberbuddy-io/open-source-contribution-for-beginners#89]
You all can add D.S files here. I have already created an array, linked list, stack, and Queue folder. you all can add files respecitively.

**Comment by pacific-prashant** [comment]
I'm adding a binary search program for array #89

**Comment by lovishprabhakar02** [comment]
Go ahead! @pacific-prashant

**Comment by pacific-prashant** [comment]
Adding Linear search and insertion at index program  in array folder

**Comment by pacific-prashant** [comment]
adding a left array rotation program  #89

**Comment by pacific-prashant** [comment]
Adding a linked list insertion file at the linked list folder.  #89

**Comment by pacific-prashant** [comment]
Adding a cycle detection in the link list program #89.

**Comment by pacific-prashant** [comment]
Adding cpp link list programs

**Comment by pacific-prashant** [comment]
adding stack file #89
