### ISSUE TITLE
Adding Kivy Files

### ISSUE THREAD

**Issue by logic-404** [cyberbuddy-io/open-source-contribution-for-beginners#93]
I want to change the theme to light

**Comment by lovishprabhakar02** [comment]
Go ahead! @logic-404

**Comment by cyberbuddy-manas** [comment]
@logic-404 Thanks for contributing to the repository. Those who'll wish to contribute in the Kivy will be able to add their codes in your folder, all thanks to your contribution. Hope to see more from you in the future. Have a great New year
